### ISSUE TITLE
Conversion error class WeatherData

### ISSUE THREAD

**Issue by wybrands4oowv** [EntwicklerOOWV/SmartWaterTankController#1]
The values in the JSON file from the endpoint are provided as integers in the unit [1/100 mm]. In the app, the values are then displayed in [mm]. This leads to incorrect presentation and also incorrect control. That means the values need to be divided by 100 to get the unit in [mm].

**Comment by JanSamusQF** [comment]
Resolved in commit [8461dfe](https://github.com/OOWVxQF/Smartwatertank-Controller/commit/8461dfe0e8df6652bdb600831adf3fc7305f7bb0)

**Comment by wybrands4oowv** [comment]
> Resolved in commit [8461dfe](https://github.com/OOWVxQF/Smartwatertank-Controller/commit/8461dfe0e8df6652bdb600831adf3fc7305f7bb0)

correction: Resolved in commit [6dde878](https://github.com/EntwicklerOOWV/SmartWaterTankController/commit/6dde878147f468cae9cf9ba713738b319e4c2cb8)

@JanSamusQF  the upper link points to the OOWVxQF account. Is it possible to deactivate the OOWVxQF account?

**Comment by JanSamusQF** [comment]
Thanks for the correction. The repositories are set to private now.
